//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CRMSecurityProvider.crm3.metadataservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MetadataServiceSoap", Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class MetadataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveEntityMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveAttributeMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimestampOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MetadataService() {
            this.Url = global::CRMSecurityProvider.Properties.Settings.Default.CRMSecurityProvider_crm3_metadataservice_MetadataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveMetadataCompletedEventHandler RetrieveMetadataCompleted;
        
        /// <remarks/>
        public event RetrieveEntityMetadataCompletedEventHandler RetrieveEntityMetadataCompleted;
        
        /// <remarks/>
        public event RetrieveAttributeMetadataCompletedEventHandler RetrieveAttributeMetadataCompleted;
        
        /// <remarks/>
        public event GetTimestampCompletedEventHandler GetTimestampCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/crm/2006/WebServices/RetrieveMetadata", RequestNamespace="http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Metadata RetrieveMetadata(MetadataFlags flags) {
            object[] results = this.Invoke("RetrieveMetadata", new object[] {
                        flags});
            return ((Metadata)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveMetadataAsync(MetadataFlags flags) {
            this.RetrieveMetadataAsync(flags, null);
        }
        
        /// <remarks/>
        public void RetrieveMetadataAsync(MetadataFlags flags, object userState) {
            if ((this.RetrieveMetadataOperationCompleted == null)) {
                this.RetrieveMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveMetadataOperationCompleted);
            }
            this.InvokeAsync("RetrieveMetadata", new object[] {
                        flags}, this.RetrieveMetadataOperationCompleted, userState);
        }
        
        private void OnRetrieveMetadataOperationCompleted(object arg) {
            if ((this.RetrieveMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveMetadataCompleted(this, new RetrieveMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/crm/2006/WebServices/RetrieveEntityMetadata", RequestNamespace="http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EntityMetadata RetrieveEntityMetadata(string entityName, EntityFlags flags) {
            object[] results = this.Invoke("RetrieveEntityMetadata", new object[] {
                        entityName,
                        flags});
            return ((EntityMetadata)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveEntityMetadataAsync(string entityName, EntityFlags flags) {
            this.RetrieveEntityMetadataAsync(entityName, flags, null);
        }
        
        /// <remarks/>
        public void RetrieveEntityMetadataAsync(string entityName, EntityFlags flags, object userState) {
            if ((this.RetrieveEntityMetadataOperationCompleted == null)) {
                this.RetrieveEntityMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveEntityMetadataOperationCompleted);
            }
            this.InvokeAsync("RetrieveEntityMetadata", new object[] {
                        entityName,
                        flags}, this.RetrieveEntityMetadataOperationCompleted, userState);
        }
        
        private void OnRetrieveEntityMetadataOperationCompleted(object arg) {
            if ((this.RetrieveEntityMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveEntityMetadataCompleted(this, new RetrieveEntityMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/crm/2006/WebServices/RetrieveAttributeMetadata", RequestNamespace="http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AttributeMetadata RetrieveAttributeMetadata(string entityName, string attributeName) {
            object[] results = this.Invoke("RetrieveAttributeMetadata", new object[] {
                        entityName,
                        attributeName});
            return ((AttributeMetadata)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveAttributeMetadataAsync(string entityName, string attributeName) {
            this.RetrieveAttributeMetadataAsync(entityName, attributeName, null);
        }
        
        /// <remarks/>
        public void RetrieveAttributeMetadataAsync(string entityName, string attributeName, object userState) {
            if ((this.RetrieveAttributeMetadataOperationCompleted == null)) {
                this.RetrieveAttributeMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAttributeMetadataOperationCompleted);
            }
            this.InvokeAsync("RetrieveAttributeMetadata", new object[] {
                        entityName,
                        attributeName}, this.RetrieveAttributeMetadataOperationCompleted, userState);
        }
        
        private void OnRetrieveAttributeMetadataOperationCompleted(object arg) {
            if ((this.RetrieveAttributeMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAttributeMetadataCompleted(this, new RetrieveAttributeMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/crm/2006/WebServices/GetTimestamp", RequestNamespace="http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTimestamp() {
            object[] results = this.Invoke("GetTimestamp", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTimestampAsync() {
            this.GetTimestampAsync(null);
        }
        
        /// <remarks/>
        public void GetTimestampAsync(object userState) {
            if ((this.GetTimestampOperationCompleted == null)) {
                this.GetTimestampOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimestampOperationCompleted);
            }
            this.InvokeAsync("GetTimestamp", new object[0], this.GetTimestampOperationCompleted, userState);
        }
        
        private void OnGetTimestampOperationCompleted(object arg) {
            if ((this.GetTimestampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimestampCompleted(this, new GetTimestampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public enum MetadataFlags {
        
        /// <remarks/>
        EntitiesOnly = 1,
        
        /// <remarks/>
        IncludeAttributes = 2,
        
        /// <remarks/>
        IncludeRelationships = 4,
        
        /// <remarks/>
        IncludePrivileges = 8,
        
        /// <remarks/>
        All = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class Metadata {
        
        private EntityMetadata[] entitiesField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entity", IsNullable=false)]
        public EntityMetadata[] Entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class EntityMetadata {
        
        private string nameField;
        
        private int objectTypeCodeField;
        
        private string displayNameField;
        
        private string displayCollectionNameField;
        
        private string descriptionField;
        
        private bool isCustomEntityField;
        
        private bool isCustomEntityFieldSpecified;
        
        private bool isCustomizableField;
        
        private bool isCustomizableFieldSpecified;
        
        private string reportViewNameField;
        
        private string primaryFieldField;
        
        private string primaryKeyField;
        
        private OwnershipTypes ownershipTypeField;
        
        private AttributeMetadata[] attributesField;
        
        private RelationshipMetadata[] referencesFromField;
        
        private RelationshipMetadata[] referencesToField;
        
        private SecurityPrivilege[] privilegesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ObjectTypeCode {
            get {
                return this.objectTypeCodeField;
            }
            set {
                this.objectTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayCollectionName {
            get {
                return this.displayCollectionNameField;
            }
            set {
                this.displayCollectionNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCustomEntity {
            get {
                return this.isCustomEntityField;
            }
            set {
                this.isCustomEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCustomEntitySpecified {
            get {
                return this.isCustomEntityFieldSpecified;
            }
            set {
                this.isCustomEntityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsCustomizable {
            get {
                return this.isCustomizableField;
            }
            set {
                this.isCustomizableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCustomizableSpecified {
            get {
                return this.isCustomizableFieldSpecified;
            }
            set {
                this.isCustomizableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReportViewName {
            get {
                return this.reportViewNameField;
            }
            set {
                this.reportViewNameField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryField {
            get {
                return this.primaryFieldField;
            }
            set {
                this.primaryFieldField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryKey {
            get {
                return this.primaryKeyField;
            }
            set {
                this.primaryKeyField = value;
            }
        }
        
        /// <remarks/>
        public OwnershipTypes OwnershipType {
            get {
                return this.ownershipTypeField;
            }
            set {
                this.ownershipTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)]
        public AttributeMetadata[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("From", IsNullable=false)]
        public RelationshipMetadata[] ReferencesFrom {
            get {
                return this.referencesFromField;
            }
            set {
                this.referencesFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("To", IsNullable=false)]
        public RelationshipMetadata[] ReferencesTo {
            get {
                return this.referencesToField;
            }
            set {
                this.referencesToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Privilege", IsNullable=false)]
        public SecurityPrivilege[] Privileges {
            get {
                return this.privilegesField;
            }
            set {
                this.privilegesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public enum OwnershipTypes {
        
        /// <remarks/>
        UnOwned = 1,
        
        /// <remarks/>
        UserOwned = 2,
        
        /// <remarks/>
        BusinessOwned = 4,
        
        /// <remarks/>
        OrgOwned = 8,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PicklistAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FloatAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DecimalAttributeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoneyAttributeMetadata))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class AttributeMetadata {
        
        private string nameField;
        
        private AttributeType typeField;
        
        private string displayNameField;
        
        private string descriptionField;
        
        private bool isCustomFieldField;
        
        private AttributeRequiredLevel requiredLevelField;
        
        private object defaultValueField;
        
        private bool validForCreateField;
        
        private bool validForReadField;
        
        private bool validForUpdateField;
        
        private DisplayMasks displayMaskField;
        
        private string attributeOfField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public AttributeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCustomField {
            get {
                return this.isCustomFieldField;
            }
            set {
                this.isCustomFieldField = value;
            }
        }
        
        /// <remarks/>
        public AttributeRequiredLevel RequiredLevel {
            get {
                return this.requiredLevelField;
            }
            set {
                this.requiredLevelField = value;
            }
        }
        
        /// <remarks/>
        public object DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidForCreate {
            get {
                return this.validForCreateField;
            }
            set {
                this.validForCreateField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidForRead {
            get {
                return this.validForReadField;
            }
            set {
                this.validForReadField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidForUpdate {
            get {
                return this.validForUpdateField;
            }
            set {
                this.validForUpdateField = value;
            }
        }
        
        /// <remarks/>
        public DisplayMasks DisplayMask {
            get {
                return this.displayMaskField;
            }
            set {
                this.displayMaskField = value;
            }
        }
        
        /// <remarks/>
        public string AttributeOf {
            get {
                return this.attributeOfField;
            }
            set {
                this.attributeOfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public enum AttributeType {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Lookup,
        
        /// <remarks/>
        Memo,
        
        /// <remarks/>
        Money,
        
        /// <remarks/>
        Owner,
        
        /// <remarks/>
        PartyList,
        
        /// <remarks/>
        Picklist,
        
        /// <remarks/>
        PrimaryKey,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        UniqueIdentifier,
        
        /// <remarks/>
        Virtual,
        
        /// <remarks/>
        CalendarRules,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public enum AttributeRequiredLevel {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        SystemRequired,
        
        /// <remarks/>
        Required,
        
        /// <remarks/>
        Recommended,
        
        /// <remarks/>
        ReadOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class SecurityPrivilege {
        
        private System.Guid privilegeIdField;
        
        private PrivilegeType privilegeTypeField;
        
        private string nameField;
        
        /// <remarks/>
        public System.Guid PrivilegeId {
            get {
                return this.privilegeIdField;
            }
            set {
                this.privilegeIdField = value;
            }
        }
        
        /// <remarks/>
        public PrivilegeType PrivilegeType {
            get {
                return this.privilegeTypeField;
            }
            set {
                this.privilegeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public enum PrivilegeType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Create,
        
        /// <remarks/>
        Read,
        
        /// <remarks/>
        Write,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Assign,
        
        /// <remarks/>
        Share,
        
        /// <remarks/>
        Append,
        
        /// <remarks/>
        AppendTo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class RelationshipMetadata {
        
        private string nameField;
        
        private string referencingEntityField;
        
        private string referencedEntityField;
        
        private string referencingAttributeField;
        
        private string referencedAttributeField;
        
        private bool isCustomRelationshipField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ReferencingEntity {
            get {
                return this.referencingEntityField;
            }
            set {
                this.referencingEntityField = value;
            }
        }
        
        /// <remarks/>
        public string ReferencedEntity {
            get {
                return this.referencedEntityField;
            }
            set {
                this.referencedEntityField = value;
            }
        }
        
        /// <remarks/>
        public string ReferencingAttribute {
            get {
                return this.referencingAttributeField;
            }
            set {
                this.referencingAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferencedAttribute {
            get {
                return this.referencedAttributeField;
            }
            set {
                this.referencedAttributeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCustomRelationship {
            get {
                return this.isCustomRelationshipField;
            }
            set {
                this.isCustomRelationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusOption))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateOption))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class Option {
        
        private int optionValueField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int OptionValue {
            get {
                return this.optionValueField;
            }
            set {
                this.optionValueField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class StatusOption : Option {
        
        private int stateField;
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class StateOption : Option {
        
        private int defaultStatusField;
        
        /// <remarks/>
        public int DefaultStatus {
            get {
                return this.defaultStatusField;
            }
            set {
                this.defaultStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public enum DisplayMasks {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        PrimaryName = 2,
        
        /// <remarks/>
        ObjectTypeCode = 4,
        
        /// <remarks/>
        ValidForAdvancedFind = 8,
        
        /// <remarks/>
        ValidForForm = 16,
        
        /// <remarks/>
        ValidForGrid = 32,
        
        /// <remarks/>
        RequiredForForm = 64,
        
        /// <remarks/>
        RequiredForGrid = 128,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class PicklistAttributeMetadata : AttributeMetadata {
        
        private int nextValueField;
        
        private Option[] optionsField;
        
        /// <remarks/>
        public int NextValue {
            get {
                return this.nextValueField;
            }
            set {
                this.nextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Option[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class StatusAttributeMetadata : AttributeMetadata {
        
        private int nextValueField;
        
        private StatusOption[] optionsField;
        
        /// <remarks/>
        public int NextValue {
            get {
                return this.nextValueField;
            }
            set {
                this.nextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class StringAttributeMetadata : AttributeMetadata {
        
        private int maxLengthField;
        
        /// <remarks/>
        public int MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/Metadata")]
    public partial class StateAttributeMetadata : AttributeMetadata {
        
        private StateOption[] optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StateOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class IntegerAttributeMetadata : AttributeMetadata {
        
        private int minValueField;
        
        private int maxValueField;
        
        /// <remarks/>
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class FloatAttributeMetadata : AttributeMetadata {
        
        private float minValueField;
        
        private float maxValueField;
        
        private int precisionField;
        
        /// <remarks/>
        public float MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public float MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public int Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class DecimalAttributeMetadata : AttributeMetadata {
        
        private decimal minValueField;
        
        private decimal maxValueField;
        
        private int precisionField;
        
        /// <remarks/>
        public decimal MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public int Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class MoneyAttributeMetadata : AttributeMetadata {
        
        private double minValueField;
        
        private double maxValueField;
        
        private int precisionField;
        
        /// <remarks/>
        public double MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public double MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public int Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/crm/2006/WebServices")]
    public enum EntityFlags {
        
        /// <remarks/>
        EntityOnly = 1,
        
        /// <remarks/>
        IncludeAttributes = 2,
        
        /// <remarks/>
        IncludeRelationships = 4,
        
        /// <remarks/>
        IncludePrivileges = 8,
        
        /// <remarks/>
        All = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void RetrieveMetadataCompletedEventHandler(object sender, RetrieveMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Metadata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Metadata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void RetrieveEntityMetadataCompletedEventHandler(object sender, RetrieveEntityMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveEntityMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveEntityMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EntityMetadata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EntityMetadata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void RetrieveAttributeMetadataCompletedEventHandler(object sender, RetrieveAttributeMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAttributeMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveAttributeMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AttributeMetadata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AttributeMetadata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetTimestampCompletedEventHandler(object sender, GetTimestampCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimestampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimestampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591