using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProduct("CRMSecurityProvider.Test.dll")]
[assembly: AssemblyTitleAttribute("CRMSecurityProvider.Test")]
[assembly: AssemblyDescription("CRMSecurityProvider.Test.dll")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation")]
[assembly: AssemblyCopyright("© Sitecore Corporation 2016")]
[assembly: AssemblyTrademarkAttribute("Sitecore")]
[assembly: AssemblyVersion("2.2.0.0")]
[assembly: AssemblyFileVersion("2.2.0")]
[assembly: AssemblyInformationalVersionAttribute("2.2.0")]

