using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProduct("Microsoft Dynamics CRM Security Provider 2.3.2 rev. 170118")]
[assembly: AssemblyTitle("Microsoft Dynamics CRM Security Provider")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompanyAttribute("Sitecore Corporation")]
[assembly: AssemblyCopyright("© Sitecore Corporation 2017")]
[assembly: AssemblyTrademarkAttribute("Sitecore")]
[assembly: AssemblyVersion("2.3.0.0")]
[assembly: AssemblyFileVersion("2.3.2")]
[assembly: AssemblyInformationalVersionAttribute("2.3.2 rev. 170118")]
